### PR TITLE
creating 0.2 test folder

### PR DESCRIPTION
**Pull request by dtgerson**

### CODE REVIEW

**Comment by gracecanfield** [comment]
@dtgerson @inceptionev - I made some updates to both files to add some additional explanatory text and cross-link these pages from each other and from the `testing-data` README. I also made 2 content changes to the template file:
* Changed "software repo & branch name" to: "Software version (link to specific commit by hash so we know the state of the software you tested):"
  * Rationale: Branches are temporary, so the best way to see the state of the software at the time of testing is to link to a commit)
* Added a new data point to the template: `Ventilator prototype serial #:` (@martukas mentioned these are now a thing, so will be a good identifying characteristic)

**Comment by inceptionev** [comment]
quick request: I'm not a fan of the mmddyyyy format.  It doesn't sort chronologically.  Can we use yyyymmdd instead?  

also, is quality assurance the right place for this?  Many of these are engineering tests.  I kind of feel like the folder 'testing' is important enough to deserve it's own folder right inside the root SystemDesign folder.  thoughts?

otherwise, it looks good.

**Comment by gracecanfield** [comment]
@inceptionev 

>I'm not a fan of the mmddyyyy format. It doesn't sort chronologically. Can we use yyyymmdd instead?

Really good point. I can update across the board.

>also, is quality assurance the right place for this? Many of these are engineering tests. I kind of feel like the folder 'testing' is important enough to deserve it's own folder right inside the root SystemDesign folder. thoughts?

So we thought the same thing about Characterization tests, so the way we handled those was to store them within the `research-development` folder. There is a [characterization test plan file here](https://github.com/RespiraWorks/SystemDesign/blob/master/research-development/characterization-test-plan.md), that links out to individual component folders with testing data. For example, fan characterization tests can be found from `/research-development/project-fan/characterization-tests' [here](https://github.com/RespiraWorks/SystemDesign/tree/master/research-development/project-fan/characterization-tests).

For these tests, if they aren't verifying or validating that the ventilator works as expected or as spec'd, then I don't think they belong in quality assurance. If they _are_ intended to validate whether the ventilator works as expected, then I'd argue they do belong there. You know more about the nuances and goals of these tests than I do. Thoughts?

**Comment by gracecanfield** [comment]
Small update: Just committed a change that adjusts the date format of the test data folders and also removed the serial # reference from the README template and replaced with a prompt to add a pic of the ventilator prototype being used for testing.

**Comment by dtgerson** [comment]
I don't believe we should put these tests with the characterization tests - that was meant more for pneumatic characterization. I am fine putting them elsewhere - but quality assurance seemed like the best fit in the current structure and if this data is going to be part of our submission for covent, it seemed applicable (ie these tests are part of our validation of the v0.2 design). But I am fine moving the v0.2 folder to research and development.

Grace - besides just for picture, can you ask for a short description of the test setups main components?

I also just pushed an update to put units for things to avoid some ambiguity

**Comment by gracecanfield** [comment]
>Grace - besides just for picture, can you ask for a short description of the test setups main components?

[Done!](https://github.com/RespiraWorks/SystemDesign/blob/test_folder/quality-assurance/testing/testing-data/v0.2/test-README-template.md)

>I am fine putting them elsewhere - but quality assurance seemed like the best fit in the current structure and if this data is going to be part of our submission for covent, it seemed applicable (ie these tests are part of our validation of the v0.2 design).

If these tests are part of the validation of our design, then I  totally agree with @dtgerson that they belong in `quality-assurance`.

**Comment by inceptionev** [comment]
thanks for your comments.  My concern is the fragmentation of test data.  If we are doing similar kinds of tests for engineering and for quality assurance they should be in the same format and kept in the same place.  What I am envisioning is a top level folder called Test Data, with Characterization, Engineering, and Quality Assurance folders inside.  I'm not willing to die on this hill though, so if it make sense to you two to keep it separate, lets just go with that.

**Comment by inceptionev** [comment]
Case in point, there is also VentilatorSoftware/sample-data

From @jlebar : It's important to us that our sample data live in the same repository as the code, because it allows us to figure out, at exactly which revision of the code was this sample data generated

**Comment by martukas** [comment]
Hashtag merge repos. Hashtag die on this hill 😉

**Comment by gracecanfield** [comment]
Agree with @martukas that the ultimate goal should be to combine all of the repos so we have a single source of truth. But this is a bigger-picture thing to think about outside of the context of this thread. 

@inceptionev I am not tied to the idea of the test data living under `quality-assurance`. I could see a scenario where all test data lives in one place, and then we could cross-link from test plans that live in the `quality-assurance` folder, and also cross-link from other places as needed.

@dtgerson If you're open to that, I'd be happy to make the folder/file updates accordingly (though it wouldn't be till later tonight). Or, if getting this data live is the immediate goal, feel free to merge without me and we could come back to the structure thing later.

**Comment by gracecanfield** [comment]
Okay - I'm actually gonna go ahead and get this merged for now. I added a [Workast task](https://respiraworks.workast.io/task/cb28daba5ede678fda5e3d9b6acb1786) to revisit this topic, because I think it could ultimately be worth reorganizing to consolidate under one test-data root-level folder, but we've got bigger fish to fry this week...

**Pull request merged**
