### PR TITLE
Create readme.md

### PR DESCRIPTION
**Pull request by esc-works**

### CODE REVIEW

**Comment by martukas** [comment]
What exactly is going on here? :)

**Comment by esc-works** [comment]
I was trying to make a folder to upload data. I should stop using the web
interface I guess
-Ethan

**Comment by gracecanfield** [comment]
@esc-works Hi! What is the adicht file (purpose of the file)?

**Comment by gracecanfield** [comment]
@esc-works Also, could you note the purpose of the LabChart folder? (So I'm aware of the thinking architecture-wise and for maintenance purposes.)

**Comment by gracecanfield** [comment]
From Ethan: The labchart folder is 
>basically a dumping ground for data we take the the instrumentation suite provided by AD instruments. 

Waiting for additional info on what the data is showing/used for so we can verify the best spot in the system architecture.

**Comment by esc-works** [comment]
Can I reply here? We got medical grade equipment from ADInstruments, the
data acquisition system is called LabChart. I wanted a place to upload the
data we collect there. We may want to start putting a test plan in place.
Dave gerson had starting working one out, we didn't really get to much of
it on the first day. I wanted to see if people could interface with the
data at all and get a sense of its structure. But then I learned labchart
can export to text file so that should be easier.
-Ethan

**Pull request merged**
